version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: deploy/docker/server/Dockerfile
      target: builder
      args:
        go_release: debug
    command: ["make", "debug"]
    volumes:
      - ./graphql:/home/appuser/app:cached
    ports:
      - 4000:4000
